name: e_maintenance
description: E-Maintenance mobile app for vehicle inspection and reporting.

publish_to: 'none'

version: 3.0.1+16

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.5.5
  http: ^1.6.0
  image_picker: ^1.2.1
  qr_code_scanner:
    path: third_party/qr_code_scanner
  intl: ^0.18.1
  permission_handler: ^12.0.1
  excel: ^4.0.6
  path: ^1.9.1
  
  # zebrautility: ^0.0.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.34
  path_provider_windows: ^2.3.0
  shared_preferences_windows: ^2.4.1
  win32: ^6.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FA520F"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FA520F"
    theme_color: "#FA520F"

flutter:

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Reg.ttf

  uses-material-design: true

  assets:
    - assets/icon.png
